# Railway Configuration
# This file is used by Railway to configure the deployment

[build]
  builder = "DOCKERFILE"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
